/* Green Team */

DROP TABLE Registrations CASCADE CONSTRAINTS;
DROP TABLE Purchases CASCADE CONSTRAINTS;
DROP TABLE Devices CASCADE CONSTRAINTS;
DROP TABLE DeviceModels CASCADE CONSTRAINTS;
DROP TABLE EventTypes CASCADE CONSTRAINTS;
DROP TABLE Events CASCADE CONSTRAINTS;
DROP TABLE EmailAddresses CASCADE CONSTRAINTS;
DROP TABLE EmailCampaigns CASCADE CONSTRAINTS;
DROP TABLE Customers CASCADE CONSTRAINTS;
DROP TABLE EventLinkLookUp CASCADE CONSTRAINTS;
