/* Green Team */

DROP TABLE IF EXISTS Registrations CASCADE;
DROP TABLE IF EXISTS Purchases CASCADE;
DROP TABLE IF EXISTS Devices CASCADE;
DROP TABLE IF EXISTS DeviceModels CASCADE;
DROP TABLE IF EXISTS EventLinkLookUp CASCADE;
DROP TABLE IF EXISTS Links CASCADE;
DROP TABLE IF EXISTS Events CASCADE;
DROP TABLE IF EXISTS EventTypes CASCADE;
DROP TABLE IF EXISTS EmailMessagesSent CASCADE;
DROP TABLE IF EXISTS EmailMessages CASCADE;
DROP TABLE IF EXISTS EmailAddresses CASCADE;
DROP TABLE IF EXISTS Customers CASCADE;
