INSERT INTO EventType VALUES(0, "Click");
INSERT INTO EventType VALUES(2, "Email Opened");
INSERT INTO EventType VALUES(11, "Complaint");
INSERT INTO EventType VALUES(20, "Email Sent/Delivered");
INSERT INTO EventType VALUES(37, "Unsubscribe");
INSERT INTO EventType VALUES(38, "Unknown bounce");
INSERT INTO EventType VALUES(39, "Technical/Other bounce");
INSERT INTO EventType VALUES(40, "Hard bounce");
INSERT INTO EventType VALUES(41, "Soft bounce");
INSERT INTO EventType VALUES(42, "Block bounce");
INSERT INTO EventType VALUES(43, "NotSent");
