INSERT INTO RegistrationLocation VALUES(14, "Contact Us");
INSERT INTO RegistrationLocation VALUES(41, "XYZ online");
INSERT INTO RegistrationLocation VALUES(42, "XYZ off line");
INSERT INTO RegistrationLocation VALUES(43, "Call Center");
INSERT INTO RegistrationLocation VALUES(44, "Rebate");
INSERT INTO RegistrationLocation VALUES(46, "Warranty bill");
INSERT INTO RegistrationLocation VALUES(47, "Extented warranty");
INSERT INTO RegistrationLocation VALUES(72, "Social Networking Site");
INSERT INTO RegistrationLocation VALUES(84, "BrandX Account Website PC");
INSERT INTO RegistrationLocation VALUES(86, "BrandX Account Website Mobile");
INSERT INTO RegistrationLocation VALUES(88, "BrandX Account Website Tablet");
INSERT INTO RegistrationLocation VALUES(90, "BrandX Account - Mobile Device");
INSERT INTO RegistrationLocation VALUES(92, "BrandX Account - TV");
INSERT INTO RegistrationLocation VALUES(107, "BrandX Historical Data");
