DROP TABLE IF EXISTS Events;

DROP TABLE IF EXISTS EventTypes;

DROP TABLE IF EXISTS Links;

DROP TABLE IF EXISTS Messages;

DROP TABLE IF EXISTS Campaigns;

DROP TABLE IF EXISTS Emails;

DROP TABLE IF EXISTS Registrations;

DROP TABLE IF EXISTS Customers;

DROP TABLE IF EXISTS Devices;

DROP TABLE IF EXISTS RegSrcs;
